import './globals.css'
import { Navbar } from './components/Navbar'
import Header from './components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Header />
        {children}
      </body>
    </html>
  )
}
